-- OCR-2541: put the TXNS transaction id generator into ordered mode.
--
-- Run once per Oracle metastore schema. Not part of the upgrade chain: clusters already at
-- schema 3.1.4 never re-run an upgrade step, and the statement needed differs depending on
-- how the schema was created, so this cannot be applied blindly.
--
-- WHY
--   Oracle defaults sequences and identity columns to NOORDER. On RAC each instance caches
--   its own block of values, so TXN_IDs stop increasing with time. The metastore relies on
--   that ordering in two places: getOpenTxnsList treats an id missing below the high water
--   mark as an open transaction, and a reader excludes every id above its own. An id issued
--   out of order therefore leaves an already committed writer above a later reader's high
--   water mark, that writer's write id is reported as still open, and the table reads empty.
--   No error is raised, so the query simply returns nothing.
--
-- WHO IS AFFECTED
--   Any Oracle metastore on a database with more than one active instance. A single instance
--   draws from one shared cache and stays ordered, so it is not exposed. Confirm with:
--
--     SELECT instance_number, instance_name, status FROM gv$instance;
--
-- COST
--   ORDER makes Oracle coordinate allocation across instances. Keep CACHE as it is: ordering
--   is what correctness depends on, and removing the cache only costs throughput. Gaps in the
--   id sequence are expected and harmless either way, because the metastore fills them.
--
-- Both statements below take effect on the next value generated. Neither changes data, needs
-- a restart, or requires an outage, and both reverse with NOORDER. Apply in a non-production
-- schema first.
--
-- Connect as the metastore schema owner. The user_* views below resolve to the connected
-- schema, so running this as SYS or as the wrong owner reports nothing and changes nothing.

-- Which case applies. Exactly one of these returns a row for the schema in use.
--   case A -> a named sequence, created by upgrade-3.2.0-to-3.1.4.3.2.2.0-1
SELECT sequence_name, cache_size, order_flag FROM user_sequences
  WHERE sequence_name = 'TXNS_TXN_ID_SEQ';
--   case B -> an identity column, created by a fresh install of hive-schema-3.1.4
SELECT table_name, column_name, identity_options FROM user_tab_identity_cols
  WHERE table_name = 'TXNS';

-- CASE A: named sequence. Run this if the first query above returned a row.
ALTER SEQUENCE TXNS_TXN_ID_SEQ ORDER;

-- CASE B: identity column. Run this instead if the second query returned a row.
-- The backing sequence is system generated, so ALTER SEQUENCE on it raises ORA-32793 and the
-- change has to go through the column. Do not add START WITH: the only form available here is
-- START WITH LIMIT VALUE, which restarts from the highest value currently in TXNS, and TXNS is
-- pruned continuously. Ids far above the surviving rows are still referenced by
-- TXN_TO_WRITE_ID and COMPLETED_TXN_COMPONENTS, so restarting would reissue them.
-- ALTER TABLE TXNS MODIFY (TXN_ID GENERATED BY DEFAULT AS IDENTITY (ORDER));

-- Verify. ORDER_FLAG must read Y for the generator actually in use.
SELECT sequence_name, cache_size, order_flag FROM user_sequences
  WHERE sequence_name = 'TXNS_TXN_ID_SEQ';
SELECT table_name, column_name, identity_options FROM user_tab_identity_cols
  WHERE table_name = 'TXNS';
