/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.apache.hadoop.hive.hbase.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Employee extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -4405825569600562940L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Employee\",\"namespace\":\"org.apache.hadoop.hive.hbase.avro\",\"fields\":[{\"name\":\"employeeName\",\"type\":\"string\"},{\"name\":\"employeeID\",\"type\":\"long\"},{\"name\":\"age\",\"type\":\"long\"},{\"name\":\"gender\",\"type\":{\"type\":\"enum\",\"name\":\"Gender\",\"symbols\":[\"MALE\",\"FEMALE\"]}},{\"name\":\"contactInfo\",\"type\":{\"type\":\"record\",\"name\":\"ContactInfo\",\"fields\":[{\"name\":\"address\",\"type\":[{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"Address\",\"fields\":[{\"name\":\"address1\",\"type\":\"string\"},{\"name\":\"address2\",\"type\":\"string\"},{\"name\":\"city\",\"type\":\"string\"},{\"name\":\"zipcode\",\"type\":\"long\"},{\"name\":\"county\",\"type\":[{\"type\":\"record\",\"name\":\"HomePhone\",\"fields\":[{\"name\":\"areaCode\",\"type\":\"long\"},{\"name\":\"number\",\"type\":\"long\"}]},{\"type\":\"record\",\"name\":\"OfficePhone\",\"fields\":[{\"name\":\"areaCode\",\"type\":\"long\"},{\"name\":\"number\",\"type\":\"long\"}]},\"string\",\"null\"]},{\"name\":\"aliases\",\"type\":[{\"type\":\"array\",\"items\":\"string\"},\"null\"]},{\"name\":\"metadata\",\"type\":[\"null\",{\"type\":\"map\",\"values\":\"string\"}]}]}},\"null\"]},{\"name\":\"homePhone\",\"type\":\"HomePhone\"},{\"name\":\"officePhone\",\"type\":\"OfficePhone\"}]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Employee> ENCODER =
      new BinaryMessageEncoder<Employee>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Employee> DECODER =
      new BinaryMessageDecoder<Employee>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<Employee> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<Employee> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Employee>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this Employee to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a Employee from a ByteBuffer. */
  public static Employee fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence employeeName;
  @Deprecated public long employeeID;
  @Deprecated public long age;
  @Deprecated public org.apache.hadoop.hive.hbase.avro.Gender gender;
  @Deprecated public org.apache.hadoop.hive.hbase.avro.ContactInfo contactInfo;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Employee() {}

  /**
   * All-args constructor.
   * @param employeeName The new value for employeeName
   * @param employeeID The new value for employeeID
   * @param age The new value for age
   * @param gender The new value for gender
   * @param contactInfo The new value for contactInfo
   */
  public Employee(java.lang.CharSequence employeeName, java.lang.Long employeeID, java.lang.Long age, org.apache.hadoop.hive.hbase.avro.Gender gender, org.apache.hadoop.hive.hbase.avro.ContactInfo contactInfo) {
    this.employeeName = employeeName;
    this.employeeID = employeeID;
    this.age = age;
    this.gender = gender;
    this.contactInfo = contactInfo;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return employeeName;
    case 1: return employeeID;
    case 2: return age;
    case 3: return gender;
    case 4: return contactInfo;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: employeeName = (java.lang.CharSequence)value$; break;
    case 1: employeeID = (java.lang.Long)value$; break;
    case 2: age = (java.lang.Long)value$; break;
    case 3: gender = (org.apache.hadoop.hive.hbase.avro.Gender)value$; break;
    case 4: contactInfo = (org.apache.hadoop.hive.hbase.avro.ContactInfo)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'employeeName' field.
   * @return The value of the 'employeeName' field.
   */
  public java.lang.CharSequence getEmployeeName() {
    return employeeName;
  }

  /**
   * Sets the value of the 'employeeName' field.
   * @param value the value to set.
   */
  public void setEmployeeName(java.lang.CharSequence value) {
    this.employeeName = value;
  }

  /**
   * Gets the value of the 'employeeID' field.
   * @return The value of the 'employeeID' field.
   */
  public java.lang.Long getEmployeeID() {
    return employeeID;
  }

  /**
   * Sets the value of the 'employeeID' field.
   * @param value the value to set.
   */
  public void setEmployeeID(java.lang.Long value) {
    this.employeeID = value;
  }

  /**
   * Gets the value of the 'age' field.
   * @return The value of the 'age' field.
   */
  public java.lang.Long getAge() {
    return age;
  }

  /**
   * Sets the value of the 'age' field.
   * @param value the value to set.
   */
  public void setAge(java.lang.Long value) {
    this.age = value;
  }

  /**
   * Gets the value of the 'gender' field.
   * @return The value of the 'gender' field.
   */
  public org.apache.hadoop.hive.hbase.avro.Gender getGender() {
    return gender;
  }

  /**
   * Sets the value of the 'gender' field.
   * @param value the value to set.
   */
  public void setGender(org.apache.hadoop.hive.hbase.avro.Gender value) {
    this.gender = value;
  }

  /**
   * Gets the value of the 'contactInfo' field.
   * @return The value of the 'contactInfo' field.
   */
  public org.apache.hadoop.hive.hbase.avro.ContactInfo getContactInfo() {
    return contactInfo;
  }

  /**
   * Sets the value of the 'contactInfo' field.
   * @param value the value to set.
   */
  public void setContactInfo(org.apache.hadoop.hive.hbase.avro.ContactInfo value) {
    this.contactInfo = value;
  }

  /**
   * Creates a new Employee RecordBuilder.
   * @return A new Employee RecordBuilder
   */
  public static org.apache.hadoop.hive.hbase.avro.Employee.Builder newBuilder() {
    return new org.apache.hadoop.hive.hbase.avro.Employee.Builder();
  }

  /**
   * Creates a new Employee RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Employee RecordBuilder
   */
  public static org.apache.hadoop.hive.hbase.avro.Employee.Builder newBuilder(org.apache.hadoop.hive.hbase.avro.Employee.Builder other) {
    return new org.apache.hadoop.hive.hbase.avro.Employee.Builder(other);
  }

  /**
   * Creates a new Employee RecordBuilder by copying an existing Employee instance.
   * @param other The existing instance to copy.
   * @return A new Employee RecordBuilder
   */
  public static org.apache.hadoop.hive.hbase.avro.Employee.Builder newBuilder(org.apache.hadoop.hive.hbase.avro.Employee other) {
    return new org.apache.hadoop.hive.hbase.avro.Employee.Builder(other);
  }

  /**
   * RecordBuilder for Employee instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Employee>
    implements org.apache.avro.data.RecordBuilder<Employee> {

    private java.lang.CharSequence employeeName;
    private long employeeID;
    private long age;
    private org.apache.hadoop.hive.hbase.avro.Gender gender;
    private org.apache.hadoop.hive.hbase.avro.ContactInfo contactInfo;
    private org.apache.hadoop.hive.hbase.avro.ContactInfo.Builder contactInfoBuilder;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.apache.hadoop.hive.hbase.avro.Employee.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.employeeName)) {
        this.employeeName = data().deepCopy(fields()[0].schema(), other.employeeName);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.employeeID)) {
        this.employeeID = data().deepCopy(fields()[1].schema(), other.employeeID);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.age)) {
        this.age = data().deepCopy(fields()[2].schema(), other.age);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.gender)) {
        this.gender = data().deepCopy(fields()[3].schema(), other.gender);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.contactInfo)) {
        this.contactInfo = data().deepCopy(fields()[4].schema(), other.contactInfo);
        fieldSetFlags()[4] = true;
      }
      if (other.hasContactInfoBuilder()) {
        this.contactInfoBuilder = org.apache.hadoop.hive.hbase.avro.ContactInfo.newBuilder(other.getContactInfoBuilder());
      }
    }

    /**
     * Creates a Builder by copying an existing Employee instance
     * @param other The existing instance to copy.
     */
    private Builder(org.apache.hadoop.hive.hbase.avro.Employee other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.employeeName)) {
        this.employeeName = data().deepCopy(fields()[0].schema(), other.employeeName);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.employeeID)) {
        this.employeeID = data().deepCopy(fields()[1].schema(), other.employeeID);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.age)) {
        this.age = data().deepCopy(fields()[2].schema(), other.age);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.gender)) {
        this.gender = data().deepCopy(fields()[3].schema(), other.gender);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.contactInfo)) {
        this.contactInfo = data().deepCopy(fields()[4].schema(), other.contactInfo);
        fieldSetFlags()[4] = true;
      }
      this.contactInfoBuilder = null;
    }

    /**
      * Gets the value of the 'employeeName' field.
      * @return The value.
      */
    public java.lang.CharSequence getEmployeeName() {
      return employeeName;
    }

    /**
      * Sets the value of the 'employeeName' field.
      * @param value The value of 'employeeName'.
      * @return This builder.
      */
    public org.apache.hadoop.hive.hbase.avro.Employee.Builder setEmployeeName(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.employeeName = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'employeeName' field has been set.
      * @return True if the 'employeeName' field has been set, false otherwise.
      */
    public boolean hasEmployeeName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'employeeName' field.
      * @return This builder.
      */
    public org.apache.hadoop.hive.hbase.avro.Employee.Builder clearEmployeeName() {
      employeeName = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'employeeID' field.
      * @return The value.
      */
    public java.lang.Long getEmployeeID() {
      return employeeID;
    }

    /**
      * Sets the value of the 'employeeID' field.
      * @param value The value of 'employeeID'.
      * @return This builder.
      */
    public org.apache.hadoop.hive.hbase.avro.Employee.Builder setEmployeeID(long value) {
      validate(fields()[1], value);
      this.employeeID = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'employeeID' field has been set.
      * @return True if the 'employeeID' field has been set, false otherwise.
      */
    public boolean hasEmployeeID() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'employeeID' field.
      * @return This builder.
      */
    public org.apache.hadoop.hive.hbase.avro.Employee.Builder clearEmployeeID() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'age' field.
      * @return The value.
      */
    public java.lang.Long getAge() {
      return age;
    }

    /**
      * Sets the value of the 'age' field.
      * @param value The value of 'age'.
      * @return This builder.
      */
    public org.apache.hadoop.hive.hbase.avro.Employee.Builder setAge(long value) {
      validate(fields()[2], value);
      this.age = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'age' field has been set.
      * @return True if the 'age' field has been set, false otherwise.
      */
    public boolean hasAge() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'age' field.
      * @return This builder.
      */
    public org.apache.hadoop.hive.hbase.avro.Employee.Builder clearAge() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'gender' field.
      * @return The value.
      */
    public org.apache.hadoop.hive.hbase.avro.Gender getGender() {
      return gender;
    }

    /**
      * Sets the value of the 'gender' field.
      * @param value The value of 'gender'.
      * @return This builder.
      */
    public org.apache.hadoop.hive.hbase.avro.Employee.Builder setGender(org.apache.hadoop.hive.hbase.avro.Gender value) {
      validate(fields()[3], value);
      this.gender = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'gender' field has been set.
      * @return True if the 'gender' field has been set, false otherwise.
      */
    public boolean hasGender() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'gender' field.
      * @return This builder.
      */
    public org.apache.hadoop.hive.hbase.avro.Employee.Builder clearGender() {
      gender = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'contactInfo' field.
      * @return The value.
      */
    public org.apache.hadoop.hive.hbase.avro.ContactInfo getContactInfo() {
      return contactInfo;
    }

    /**
      * Sets the value of the 'contactInfo' field.
      * @param value The value of 'contactInfo'.
      * @return This builder.
      */
    public org.apache.hadoop.hive.hbase.avro.Employee.Builder setContactInfo(org.apache.hadoop.hive.hbase.avro.ContactInfo value) {
      validate(fields()[4], value);
      this.contactInfoBuilder = null;
      this.contactInfo = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'contactInfo' field has been set.
      * @return True if the 'contactInfo' field has been set, false otherwise.
      */
    public boolean hasContactInfo() {
      return fieldSetFlags()[4];
    }

    /**
     * Gets the Builder instance for the 'contactInfo' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public org.apache.hadoop.hive.hbase.avro.ContactInfo.Builder getContactInfoBuilder() {
      if (contactInfoBuilder == null) {
        if (hasContactInfo()) {
          setContactInfoBuilder(org.apache.hadoop.hive.hbase.avro.ContactInfo.newBuilder(contactInfo));
        } else {
          setContactInfoBuilder(org.apache.hadoop.hive.hbase.avro.ContactInfo.newBuilder());
        }
      }
      return contactInfoBuilder;
    }

    /**
     * Sets the Builder instance for the 'contactInfo' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */
    public org.apache.hadoop.hive.hbase.avro.Employee.Builder setContactInfoBuilder(org.apache.hadoop.hive.hbase.avro.ContactInfo.Builder value) {
      clearContactInfo();
      contactInfoBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'contactInfo' field has an active Builder instance
     * @return True if the 'contactInfo' field has an active Builder instance
     */
    public boolean hasContactInfoBuilder() {
      return contactInfoBuilder != null;
    }

    /**
      * Clears the value of the 'contactInfo' field.
      * @return This builder.
      */
    public org.apache.hadoop.hive.hbase.avro.Employee.Builder clearContactInfo() {
      contactInfo = null;
      contactInfoBuilder = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Employee build() {
      try {
        Employee record = new Employee();
        record.employeeName = fieldSetFlags()[0] ? this.employeeName : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.employeeID = fieldSetFlags()[1] ? this.employeeID : (java.lang.Long) defaultValue(fields()[1]);
        record.age = fieldSetFlags()[2] ? this.age : (java.lang.Long) defaultValue(fields()[2]);
        record.gender = fieldSetFlags()[3] ? this.gender : (org.apache.hadoop.hive.hbase.avro.Gender) defaultValue(fields()[3]);
        if (contactInfoBuilder != null) {
          record.contactInfo = this.contactInfoBuilder.build();
        } else {
          record.contactInfo = fieldSetFlags()[4] ? this.contactInfo : (org.apache.hadoop.hive.hbase.avro.ContactInfo) defaultValue(fields()[4]);
        }
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Employee>
    WRITER$ = (org.apache.avro.io.DatumWriter<Employee>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Employee>
    READER$ = (org.apache.avro.io.DatumReader<Employee>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
